#ifndef FIRMWARE_VERSION_H
#define FIRMWARE_VERSION_H

#define FW_VERSION_MAJOR 1
#define FW_VERSION_MINOR 5
#define FW_VERSION_PATCH 1

#define FW_BUILD_DATE "2025-11-23"

#endif // FIRMWARE_VERSION_H
